---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "grafana.fullname" . }}-configmap
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
data:
  {{- with .Values.config }}
  datasources.yaml: |-
    {{- toYaml . | nindent 4 }}
  {{- end }}
