test_name: Test for testing

strict:
  - headers:off
  - json:off

stages:
  - name: authenticate and fetch access token
    request:
      url: "{tavern.env_vars.KEYCLOAK_HOST}"
      method: POST
      data:
        grant_type: client_credentials
        client_id: "{tavern.env_vars.KEYCLOAK_CLIENT_ID}"
        client_secret: "{tavern.env_vars.KEYCLOAK_CLIENT_SECRET}"
    response:
      status_code: 200
      json:
        token_type: Bearer
      headers:
        content-type: application/json
      save:
        json:
          access_token: access_token

  - name: get all COMPLETED jobs
    request:
      url: "{tavern.env_vars.IRS_HOST}/irs/jobs?jobStates=COMPLETED"
#      json:
#        globalAssetId: urn:uuid:4ad4a1ce-beb2-42d2-bfe7c6xyz009123452
#        collectAspects: true
#        depth: 10
#        direction: "downward"
      method: GET
      headers:
        content-type: application/json
        Authorization: "Bearer {access_token:s}"
    response:
      status_code: 200
      verify_response_with:
        function: api-tests.tavern_helpers:jobs_are_COMPLETED
#      json:
#        - jobId: !anystr
#        - status: !anystr
      headers:
        content-type: application/json
      loggers:
        tavern:
          handlers:
            - stderr
          level: DEBUG