---
{{ if .Values.install.grafana }}

kind: PersistentVolume
apiVersion: v1
metadata:
  name: grafana-pv
  namespace: {{ .Release.Namespace | default "default" | quote }}
  labels:
    type: local
    app: grafana
  annotations:
    "helm.sh/resource-policy": keep    
spec:
  storageClassName: standard
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data/grafana"

{{ end }}