{{ if .Values.install.grafana }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.config.grafana.secret.name  | toString | quote }}
  namespace: {{ .Release.Namespace | default "default" | quote }}
type: Opaque
stringData:
  admin-user: {{ .Values.grafana.username | toString | quote }}
  admin-password: {{ .Values.grafana.password | toString | quote }}

{{ end }}