{{- if .Values.install.irs.backend }}
{{- if not .Values.config.irs.existingSecret }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.config.irs.secret.name | toString | quote }}
  namespace: {{ .Release.Namespace | default "default" | quote }}
type: Opaque
data:
  minioUser: {{ .Values.config.irs.secret.minio.user | b64enc | quote }}
  minioPassword: {{ .Values.config.irs.secret.minio.password | b64enc | quote }}
  keycloakClientId: {{ .Values.config.keycloak.client.id | b64enc | quote }}
  keycloakClientSecret: {{ .Values.config.keycloak.client.secret | b64enc | quote }}
  edcApiSecret: {{ .Values.config.irs.secret.edc.api.secret | b64enc | quote }}
  {{- if .Values.install.grafana }}
  grafanaUser: {{ .Values.config.irs.secret.grafana.user | b64enc | quote }}
  grafanaPassword: {{ .Values.config.irs.secret.grafana.password | b64enc | quote }}
  {{- end }}
{{- end }}
{{- end }}
