username: <path:traceability-irs/data/int/grafana#username>
password: <path:traceability-irs/data/int/grafana#password>

ingress:
  hosts:
    - host: "irs-grafana.int.demo.catena-x.net"
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - "irs-grafana.int.demo.catena-x.net"
      # Default secret for certificate creation already provided to your namespace
      secretName: tls-secret

oauthClientId: <path:traceability-irs/data/int/grafana#oauthClientId>
oauthClientSecret: <path:traceability-irs/data/int/grafana#oauthClientSecret>