server:
  port: 8080
  trustedPort: ${SERVER_TRUSTED_PORT:}

spring:
  application:
    name: item-relationship-service
  security:
    oauth2:
      client:
        registration:
          keycloak:
            authorization-grant-type: client_credentials
            client-id: ${KEYCLOAK_OAUTH2_CLIENT_ID}
            client-secret: ${KEYCLOAK_OAUTH2_CLIENT_SECRET}
        provider:
          keycloak:
            token-uri: ${KEYCLOAK_OAUTH2_CLIENT_TOKEN_URI:https://default}
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_OAUTH2_JWK_SET_URI:https://default}

management:
  endpoints:
    web:
      exposure:
        include: health, threaddump, loggers, prometheus, info, metrics
  endpoint:
    health:
      probes:
        enabled: true
      group:
        readiness:
          include: readinessState, diskSpace
      show-details: always
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        http: true
    tags:
      application: ${spring.application.name}
  server:
    port: 4004

logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    root: WARN
    org.springframework: INFO
    org.eclipse.tractusx.irs: INFO

springdoc:
  api-docs:
    path: /api/api-docs
  swagger-ui:
    path: /api/swagger-ui
  writer-with-order-by-keys: true

irs:
  apiUrl: "${IRS_API_URL:http://localhost:8080}"
  job:
    cleanup:
      scheduler:
        #          ┌───────────── second (0-59)
        #          │ ┌───────────── minute (0 - 59)
        #          │ │ ┌───────────── hour (0 - 23)
        #          │ │ │ ┌───────────── day of the month (1 - 31)
        #          │ │ │ │ ┌───────────── month (1 - 12) (or JAN-DEC)
        #          │ │ │ │ │ ┌───────────── day of the week (0 - 7)
        #          │ │ │ │ │ │          (or MON-SUN -- 0 or 7 is Sunday)
        #          │ │ │ │ │ │
        completed: 0 0 * * * * # every hour
        failed: 0 0 * * * * # every hour
    jobstore:
      ttl:
        failedInHours: 168 # 7 days
        completedInHours: 168 # 7 days
      cron:
        expression: "*/10 * * * * ?" # every 10 seconds

blobstore:
  endpoint: "${MINIO_URL}"
  accessKey: "${MINIO_ACCESS_KEY}"
  secretKey: "${MINIO_SECRET_KEY}"
  bucketName: irsbucket

resilience4j:
  retry:
    configs:
      default:
        maxAttempts: 3
        waitDuration: 10s
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
    instances:
      registry:
        baseConfig: default
      submodel:
        baseConfig: default

edc:
  controlplane:
    request-ttl: ${EDC_CONTROLPLANE_REQUEST_TTL:PT10M}
    endpoint:
      data: ${EDC_CONTROLPLANE_ENDPOINT_DATA:}
    provider-suffix: ${EDC_CONTROLPLANE_PROVIDER_SUFFIX:/api/v1/ids/data}
    catalog-limit: ${EDC_CONTROLPLANE_CATALOG_LIMIT:1000}
    api-key:
      header: ${EDC_API_KEY_HEADER:}
      secret: ${EDC_API_KEY_SECRET:}

  submodel:
    request-ttl: ${EDC_SUBMODEL_REQUEST_TTL:PT10M}
    path: ${EDC_SUBMODEL_PATH:/submodel}
    urn-prefix: ${EDC_SUBMODEL_URN_PREFIX:/urn}

digitalTwinRegistry:
  url: "${DIGITALTWINREGISTRY_URL:}"

semanticsHub:
  url: "${SEMANTICSHUB_URL:}"
  cleanup:
    #          ┌───────────── second (0-59)
    #          │ ┌───────────── minute (0 - 59)
    #          │ │ ┌───────────── hour (0 - 23)
    #          │ │ │  ┌───────────── day of the month (1 - 31)
    #          │ │ │  │ ┌───────────── month (1 - 12) (or JAN-DEC)
    #          │ │ │  │ │ ┌───────────── day of the week (0 - 7)
    #          │ │ │  │ │ │          (or MON-SUN -- 0 or 7 is Sunday)
    #          │ │ │  │ │ │
    scheduler: 0 0 23 * * * # every day at 23:00
  defaultUrns: "${SEMANTICSHUB_DEFAULT_URNS:urn:bamm:io.catenax.serial_part_typization:1.0.0#SerialPartTypization}"

bpdm:
  url: "${BPDM_URL:}"

