feign:
  client:
    config:
      digitalTwinRegistry:
        url: http://stub
      SubmodelClient:
        url: http://stub

blobstore:
  endpoint: http://localhost:9000
  accessKey: minioadmin
  secretKey: minioadmin

