feign:
  client:
    config:
      digitalTwinRegistry:
        url: http://localhost

blobstore:
  endpoint: http://localhost:9000
  accessKey: minioadmin
  secretKey: minioadmin

async:
  joborchestrator:
    maxPoolSize: 10
    poolSize: 5
    capacity: 100

irs:
  job:
    cleanup:
      scheduler:
        completed: 0 * * * * *
        failed: 0 * * * * *

