{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "minio.secretName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ template "minio.name" . }}
    chart: {{ template "minio.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  rootUser: {{ .Values.rootUser | b64enc | quote }}
  rootPassword: {{ .Values.rootPassword | b64enc | quote }}  
  minioUser: {{ .Values.rootUser | b64enc | quote }}
  minioPassword: {{ .Values.rootUser | b64enc | quote }}
{{- end }}
