nameOverride: "app-irs-dev01-minio"
fullnameOverride: "app-irs-dev01-minio"

## Set default rootUser, rootPassword
## AccessKey and secretKey is generated when not set
## Distributed MinIO ref: https://docs.minio.io/docs/distributed-minio-quickstart-guide
##
rootUser: <path:traceability-irs/data/dev/minio#minioUser>
rootPassword: <path:traceability-irs/data/dev/minio#minioPassword>

## Path where PV would be mounted on the MinIO Pod
mountPath: "/data"

## Enable persistence using Persistent Volume Claims
## ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
##
persistence:
  enabled: false


  ## Expose the MinIO service to be accessed from outside the cluster (LoadBalancer service).
## or access it from within the cluster (ClusterIP service). Set the service type and the port to serve it.
## ref: http://kubernetes.io/docs/user-guide/services/
##
minio:
  url: http://app-irs-dev01-minio:9000
