apiVersion: v1
kind: Service
metadata:
  name: irs-connector-provider
  labels:
    app.kubernetes.io/name: irs-connector-provider
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8181
      protocol: TCP
  selector:
    app.kubernetes.io/name: irs-connector-provider
