apiVersion: v1
kind: Secret
metadata:
  name: irs-secrets
type: Opaque
data:
  postgresql_username: {{ .Values.postgresql.postgresqlUsername | b64enc | quote }}
  postgresql_password: {{ .Values.postgresql.postgresqlPassword | b64enc | quote }}
