---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prometheus.fullname" . }}-configmap
  labels:
    {{- include "prometheus.labels" . | nindent 4 }}
data:
  config: |-
    {{- .Values.prometheus.yml | nindent 4 }}
