edc-controlplane:
  edc:
    postgresql:
      user: edc
      password:
    transfer:
      proxy:
        token:
          verifier:
            publickey:
              alias:
          signer:
            privatekey:
              alias:
    api:
      auth:
        key:
    controlplane:
      url:
    dataplane:
      url:
  configuration:
    properties: |-
      edc.oauth.client.id=
      edc.oauth.private.key.alias=
      edc.oauth.provider.jwks.url=
      edc.oauth.public.key.alias=
      edc.oauth.token.url=
      
      edc.vault.hashicorp.url=
      edc.vault.hashicorp.token=
      edc.vault.hashicorp.api.secret.path=
      
      edc.data.encryption.keys.alias=
      edc.data.encryption.algorithm=
