apiVersion: v1
kind: ConfigMap
metadata:
  name: irs-dataspace-config
  labels:
    app.kubernetes.io/name: irs-connector-consumer
data:
  dataspace-partitions.json: {{ .Values.dataspace.partitions.configJsonBase64 | b64dec | quote }}
  dataspace-deployments.json: {{ .Values.dataspace.partitions.deploymentsJsonBase64 | b64dec | quote }}
