apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: irs-connector-consumer
  labels:
    app.kubernetes.io/name: irs-connector-consumer
    app.kubernetes.io/part-of: irs-connector
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: irs-connector-consumer
  serviceName: "irs-connector-consumer"
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "4006"
        prometheus.io/scheme: "http"
        prometheus.io/path: "/metrics"
      labels:
        app.kubernetes.io/name: irs-connector-consumer
    spec:
      containers:
        - name: connector
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8181
              name: http
            - containerPort: 4006
              name: prometheus
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 512Mi
          env:
            - name: edc.vault.certificate
              value: /certificate/cert.pfx
            - name: irs.dataspace.partitions
              value: /config/dataspace-partitions.json
            - name: irs.dataspace.partition.deployments
              value: /config/dataspace-deployments.json
{{- range $key, $value := .Values.consumer.env }}
            - name: "{{ $key }}"
              value: "{{ $value }}"
{{- end }}

          volumeMounts:
            - name: certificate
              mountPath: "/certificate/"
              readOnly: true
            - name: config
              mountPath: "/config/"
              readOnly: true
      volumes:
        - name: certificate
          secret:
            secretName: irs-connector-consumer-certificate
        - name: config
          configMap:
            name: irs-dataspace-config
