name: Reduce docs
on:
  push:
  pull_request:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Asciidoctor Reducer
        run: sudo gem install asciidoctor-reducer

      - name: Reduce docs
        run: |
          asciidoctor-reducer -o docs/target/adminguide.adoc docs/src/docs/administration/administration-guide.adoc
          asciidoctor-reducer -o docs/target/arc42.adoc docs/src/docs/arc42/full.adoc