name: build

on:
  push:
    branches:  [ main, master ]
  pull_request:
    branches:  [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up the Java JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn package -B test

      - name: Generate JaCoCo Badge
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2
        with:
          generate-branches-badge: true
          jacoco-csv-file: >
            irs-api/target/site/jacoco/jacoco.csv
            irs-client/target/site/jacoco/jacoco.csv
            irs-common/target/site/jacoco/jacoco.csv
            irs-models/target/site/jacoco/jacoco.csv
            irs-parent/target/site/jacoco/jacoco.csv
            irs-parent-sprint-boot/target/site/jacoco/jacoco.csv
            irs-testing/target/site/jacoco/jacoco.csv

      - name: Log coverage percentage
        run: |
          echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
          echo "branch coverage = ${{ steps.jacoco.outputs.branches }}"

      - name: Commit the badge (if it changed)
        run: |
          if [[ `git status --porcelain` ]]; then
            git config --global user.name 'jacoco'
            git config --global user.email 'jacoco@users.noreply.github.com'
            git add -A
            git commit -m "Autogenerated JaCoCo coverage badge"
            git push
          fi