name: "owasp"

on:
  push:
    branches:
      - main
      - master
      - 'feature/**'
      - 'bugfix/**'
      - 'fix/**'
      - 'chore/**'

  schedule:
    - cron:  "0 0 * * *"

jobs:
  analyze:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    name: owasp-check
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.3
        with:
          maven-version: 3.8.2

      - name: Cache maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: run maven owasp plugin
        run: mvn install -Pactive
