name: "Sync main to IRS-Env"

on:
  push:
    branches: main

jobs:
  sync-branches:
    name: Sync branches
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create PR
        run: |
          gh pr create -B helm-environments -H main \
          --title Merge main into helm-environments \
          --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
