name: "Sync main to IRS-Env"

on:
  push:
    branches:
      - main
      - chore/fix-branch-sync-action

jobs:
  sync-branches:
    name: Sync branches
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Merge main into catena-x-environments
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout --progress --force -B main refs/remotes/origin/main
          git pull
          git checkout -B catena-x-environments refs/remotes/origin/catena-x-environments
          git merge main
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
