name: tavern irs api test

on:
  push:
    branches: [ main, master ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main, master ]
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
  schedule:
    - cron: '00 */1 * * 1-5'

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        language: [ 'python' ]

    services:
      docker:
        image: docker

  steps:
    - uses: actions/checkout@v2

    - name: Python setuo
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.7

    - name: install deps
      run: |
        pi install tavern
