name: Veracode Static Analysis
on:
  schedule:
    - cron: "0 10 * * *"

jobs:
  static_analysis:
    name: Static Analysis
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.3
        with:
          maven-version: 3.8.2

      - name: Build
        run: mvn package

      - uses: actions/upload-artifact@v2
        with:
          path: 'irs-api/target/*exec.jar'

      - name: Veracode Upload And Scan
        uses: veracode/veracode-uploadandscan-action@0.2.2
        with:
          appname: 'IRS'
          version: '${{ github.run_id }}'
          createprofile: false
          vid: '${{ secrets.VERACODE_API_ID }}'
          vkey: '${{ secrets.VERACODE_API_KEY }}'
          filepath: 'irs-api/target/*exec.jar'
          criticality: 'High'
          deleteIncompleteScan: 2 #delete a scan of any status except Results Ready to proceed with the uploadandscan action. If errors occur when running this action, the Java wrapper automatically deletes the incomplete scan.
