name: Veracode Static Analysis
on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main, master ]

jobs:
  static_analysis:
    name: Static Analysis
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Zip Project
        run: zip -r project.zip .* *
        env:
          build-name: project.zip
      - uses: actions/upload-artifact@v2
        with:
          path: project.zip

      - name: Veracode Upload And Scan
        uses: veracode/veracode-uploadandscan-action@0.2.1
        with:
          appname: 'IRS'
          createprofile: false
          vid: '${{ secrets.VERACODE_API_ID }}'
          vkey: '${{ secrets.VERACODE_API_KEY }}'
          filepath: 'project.zip'
          criticality: 'High'
